FROM ubuntu:22.04
LABEL maintainer="disi-unibo-nlp"

# Zero interaction (default answers to all questions)
ENV DEBIAN_FRONTEND=noninteractive

# Set work directory
WORKDIR /workdir

# Install general-purpose dependencies
RUN apt-get update -y && \
    apt-get install -y curl \
    git \
    bash \
    nano \
    wget \
    python3.11 \
    python3-pip && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN pip install wrapt --upgrade --ignore-installed

# OpenAI client installation
RUN pip install openai==1.58.1
RUN pip install pydantic==2.10.6
RUN pip install requests_cache==1.2.1
RUN pip install retry-requests==2.0.0

# API server stuff
RUN pip install fastapi==0.115.6
RUN pip install uvicorn==0.34.0

# Weather API stuff
RUN pip install pandas==2.2.3
RUN pip install openmeteo-requests==1.3.0

# Copy source code
COPY ./src/chatbot_backend.py /workdir/chatbot_backend.py
COPY ./prompts /workdir/prompts

# Back to default frontend
ENV DEBIAN_FRONTEND=dialog